### ISSUE TITLE
Kermits Code-to-code Review

### ISSUE THREAD

**Issue by Joseph-Burke** [rloterh/ElectronicsEShop#1]
The appearance of the page is excellent. 
Some cross-browser compatibility issues, be aware.
Footer; line decoration on the link.
Great work on the logo for the website.
Capitalise some words in the footer for a more professional look.
Header logo could be made into a link.
Resizing issue; before shrinking to the 768px breakpoint, there are some screen widths where content is overflowing from the html file. Max-width could potentially fix this.

**Comment by rloterh** [comment]
Thanks, team for the useful comments to improve the code and look of the project. All suggestions are implemented
